---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template:
    metadata: 
      name: bggdb-po
      labels: 
        name: bggdb-po
        dept: database
    spec:
      containers:
        - name: bggdb-container
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports: 
          - name: bggdb-port
            containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: bggdb-port

---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: bggapp-configmap
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc

---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: bggapp-po
  template:
    metadata: 
      name: bggapp-po
      labels: 
        name: bggapp-po
        dept: application
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v2
          imagePullPolicy: IfNotPresent
          ports: 
          - name: bggapp-port
            containerPort: 3000
          envFrom:
          - secretRef:
              name: bggapp-secret  
          - configMapRef:
              name: bggapp-configmap
          livenessProbe: 
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-po
  ports:
  - port: 80
    targetPort: bggapp-port

